name: Daily Script

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer dependencies
        run: |
          pip install -r requirements.txt

      - name: Kjør script
        run: python ditt_script.py